export const rightAnswers1 = {
  l1: /^der lampe$/,
  l2: /^der lampe$/,
  l3: /^die lampe$/,
  u1: /^der uhr$/,
  u2: /^der uhr$/,
  u3: /^die uhr$/,
  h1: /^des handys$/,
  h2: /^dem handy$/,
  h3: /^das handy$/,
  lo1: /^des l(ö|oe)ffels$/,
  lo2: /^dem l(ö|oe)ffel$/,
  lo3: /^den l(ö|oe)ffel$/,
  le1: /^der leute$/,
  le2: /^den leuten$/,
  le3: /^die leute$/,
  k1: /^der kinder$/,
  k2: /^den kindern$/,
  k3: /^die kinder$/,
};

export const rightAnswers2 = {
  s1: /^eine postkarte$/,
  s2: /^dem chef$/,
  s3: /^der eitrittskarte$/,
  s4: /^meines bruders$/,
  s5: /^den g(ä|ae)sten$/,
};

export const rightAnswers3 = {
  s1: /^(H|h)aus$/,
  s2: /^(O|o)ptimismus$/,
  s3: /^(B|b)esprechung$/,
  s4: /^(C|c)afés$/,
  s5: /^(K|k)osmos$/,
};

export const rightAnswers4 = {
  s1: /^(H|h)auses$/,
  s2: /^(E|e)rgebnisses$/,
  s3: /^(C|c)afés$/,
  s4: /^(K|k)osmos$/,
  s5: /^(S|s)uffixes$/,
};

export const rightAnswers5 = {
  s1: /^des vaters$/,
  s2: /^des studenten$/,
  s3: /^der nachbar$/,
  s4: /^meiner schwester$/,
  s5: /^des k(ö|oe)nigs$/,
};

export const rightAnswers8 = {
  s1: /^Dekan$/,
  s2: /^Gast$/,
  s3: /^Planeten$/,
  s4: /^Herzen$/,
  s5: /^Eltern$/,
  s6: /^Buchstaben$/,
  s7: /^Professors$/,
  s8: /^Studenten$/,
  s9: /^Glauben$/,
  s10: /^Franzosen$/,
};

export const rightAnswers9 = {
  s1: /^(B|b)erlins$/,
  s2: /^der (E|e)lbe$/,
  s3: /^den (R|r)hein$/,
  s4: /^(K|k)arls (A|a)uto$/,
  s5: /^(P|p)rofessor (K|k)ühns$/,
  s6: /^(F|f)riedrichs des (E|e)rsten$/,
  s7: /^(A|a)frikas$/,
  s8: /^(H|h)errn (G|g)asanovs$/,
};

export const rightAnswers10 = {
  s1: /^messenger$/,
  s2: /^menschen$/,
  s3: /^anfängen$/,
  s4: /^internets$/,
  s5: /^f(ä|ae)llen$/,
  s6: /^smartphones$/,
  s7: /^messenger$/,
  s8: /^funktionen$/,
  s9: /^programme$/,
  s10: /^messenger$/,
  s11: /^smartphones$/,
  s12: /^m(ö|oe)glichkeit$/,
  s13: /^familie$/,
  s14: /^freunden$/,
  s15: /^arbeitskollegen$/,
  s16: /^sekunden$/,
  s17: /^jahren$/,
  s18: /^messenger$/,
  s19: /^funktion$/,
  s20: /^videotelefonie$/,
  s21: /^sprachnachrichten$/,
  s22: /^funktionen$/,
  s23: /^nutzern$/,
  s24: /^new york$/,
  s25: /^miami$/,
  s26: /^nacht$/,
  s27: /^dem flughafen$/,
  s28: /^den flieger$/,
  s29: /^den großen teich$/,
  s30: /^europa$/,
  s31: /^dem ende$/,
  s32: /^10 minuten$/,
  s33: /^der welt$/,
  s34: /^dem flieger$/,
  s35: /^unsere kamera$/,
  s36: /^die stewardess$/,
  s37: /^dem flieger$/,
  s38: /^den kapitän$/,
  s39: /^einer (ä|ae)lteren dame$/,
  s40: /^die fotos$/,
  s41: /^bestimmten produkten$/,
  s42: /^umweltthemen$/,
  s43: /^dem thema$/,
  s44: /^fleischkonsum$/,
  s45: /^unseres klimawandels$/,
  s46: /^der heutigen zeit$/,
  s47: /^dem nachdenken$/,
  s48: /^vegetarier$/,
  s49: /^die absoluten (ö|oe)ko-menschen$/,
  s50: /^den kapit(ä|ae)n$/,
  s51: /^dem kopf$/,
};
