export const rightAnswers1 = {
  h1: /^h(oe|ö)re$/,
  h2: /^h(oe|ö)rst$/,
  h3: /^h(oe|ö)rt$/,
  h5: /^h(oe|ö)rt$/,
  h6: /^h(oe|ö)ren$/,
  k2: /^kochst$/,
  k3: /^kocht$/,
  k4: /^kochen$/,
  k5: /^kocht$/,
  k6: /^kochen$/,
  l1: /^l(ue|ü)ge$/,
  l2: /^l(ue|ü)gst$/,
  l4: /^l(ue|ü)gen$/,
  l5: /^l(ue|ü)gt$/,
  l6: /^l(ue|ü)gen$/,
  t1: /^trinke$/,
  t2: /^trinkst$/,
  t3: /^trinkt$/,
  t4: /^trinken$/,
  t5: /^trinkt$/,
  w1: /^wohne$/,
  w3: /^wohnt$/,
  w4: /^wohnen$/,
  w5: /^wohnt$/,
  w6: /^wohnen$/,
  z1: /^zeige$/,
  z2: /^zeigst$/,
  z3: /^zeigt$/,
  z4: /^zeigen$/,
  z6: /^zeigen$/,
};

export const rightAnswers2 = {
  s1: /^fragt$/,
  s2: /^wiederholt$/,
  s3: /^glaube$/,
  s4: /^kaufst du ein$/,
  s5: /^lebt$/,
};

export const rightAnswers3 = {
  s1: /^redest$/,
  s2: /^hei(ss|ß)t$/,
  s3: /^sammle$/,
  s4: /^zeichnet$/,
  s5: /^tanzt$/,
  s6: /^angle$/,
};

export const rightAnswers4 = {
  s1: /^liest$/,
  s2: /^isst$/,
  s3: /^hilfst$/,
  s4: /^siehst$/,
  s5: /^f(ä|ae)hrst$/,
  s6: /^l(ä|ae)uft$/,
};

export const rightAnswers5 = {
  s1: /^rettet$/,
  s2: /^regnet$/,
  s3: /^redest$/,
  s4: /^(ö|oe)ffnest$/,
  s5: /^atmet$/,
};

export const rightAnswers6 = {
  s1: /^isst du immer so viel gem(ü|ue)se$/,
  s2: /^du zerrei(ss|ß)t meine seele, was (kommt als nächstes|kommt weiter|weiter)\? scheidung\?$/,
  s3: /^liest du (deinen|den) vortrag einfach (vom|von dem| veon einem) blatt ab\? das kann nicht sein!?$/,
  s4: /^sitzt du oft hier\? (ich habe dich nie in vorlesungen gesehen|ich sah dich nie in vorlesung).?$/,
  s5: /^du hei(ss|ß)t andre, das ist dein (echter|realer|richtiger) name.?$/,
};

export const rightAnswers7 = {
  s1: /^fahre$/,
  s2: /^ist$/,
  s3: /^spreche$/,
  s4: /^kann$/,
  s5: /^versuche$/,
  s6: /^finde$/,
  s7: /^besuche$/,
  s71: /^wohnt$/,
  s8: /^arbeitet$/,
  s9: /^hat$/,
  s10: /^trifft$/,
  s11: /^gehen$/,
  s12: /^sitzt$/,
  s13: /^isst$/,
  s14: /^w(ae|ä)hle$/,
  s15: /^ist$/,
  s16: /^gibt$/,
  s17: /^besuchen$/,
  s18: /^mag$/,
  s19: /^fahre$/,
  s20: /^dauert$/,
  s21: /^ist$/,
  s22: /^liegt$/,
  s23: /^bietet$/,
  s24: /^stehe$/,
  s24a: /^auf$/,
  s25: /^gehe$/,
  s25a: /^spazieren$/,
  s26: /^besichtige$/,
  s27: /^genie(ss|ß)e$/,
  s28: /^habe$/,
  s29: /^bleibe$/,
  s30: /^kehre$/,
  s30a: /^zur(ue|ü)ck$/,
  s31: /^wartet$/,
  t1: /^will$/,
  t2: /^(ue|ü)berlege$/,
  t3: /^sind$/,
  t4: /^ist$/,
  t5: /^verlocken$/,
  t6: /^erhole$/,
  t6a: /^mich$/,
  t7: /^ist$/,
  t8: /^denke$/,
  t8a: /^nach$/,
};
